---
# Source: kube-prometheus-stack/charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-kube-prometheus-stack-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: kube-prometheus-stack
    chart: prometheus-node-exporter-1.12.0
    jobLabel: node-exporter
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - kube-prometheus-stack-prometheus-node-exporter
